Feature/more cleanup (#133)
* Cleanup logging

* [maven-release-plugin] prepare release 2.0-alpha.10

* [maven-release-plugin] prepare for next development iteration

* Iterate version number

* Update README.md

* I think consonance should specify the max number of nodes that should run at any one time. Otherwise, I'm seeing extra nodes provisioned!

* these were swapped

* working on code to cleanup VMs when jobs are lost

* First pass at lost job recovery, rescheduling code

* now lost jobs are counted for the total VMs that should be running

* cleanup and testing for lost jobs

* Adjusting log level

* Adding note about exposing jobhash to cli

* working on support for ens3 or other eth devices

* detecting eth dev, also adding sudo since an ubuntu user can't access docker by default

* switching to the Consonance fork of container-host-bag

* working on docs, exposing more params to the bootstrapper

* updated templates, more values from bootstrap script

* working on more params

* updated readme

* updates

* updates

* updates

* updates

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* working on more robust checking in worker

* setting pom.xml to false for failOnWarnings for the dependency tool, better error checking for worker

* updating to temp URLs

* updates to dockerfile

* updated ami example

* why can't I override on the command line?

* reap failed by default

* adding new config

* working through resubmission issues

* updating

* fixing problem with ints in the postgres object

* adding more cleanup

* update note

* Update README.md (#130)

* update readme

* Fix the compile error

* Add cache to speed up build,

Also ignore test that is not applicable anymore

* Skip coverage testing to improve runtime

diff --git a/container-admin/install_bootstrap b/container-admin/install_bootstrap
--- a/container-admin/install_bootstrap
+++ b/container-admin/install_bootstrap
@@ -2,26 +2,40 @@
 
 # Created by Solomon Shorser
 # Hacked by Denis Yuen
+# Hacked by Brian O'Connor <briandoconnor@gmail.com>
 
 set -e
 CONSONANCE_LAUNCHER_VERSION=feature/consonance_cleanup
 
 cat <<MSG
-CONSONANCE COMMAND LINE INTERFACE - INSTALLATION
------------------------------------------------
-This tool will setup a "launcher" host which has all of the infrastructure we used to align and variant call
-the PanCancer donors.  This launcher host can then launch one or more worker VMs to launch generic tools 
-and workflows registered on Dockstore.
+CONSONANCE INSTALLATION BOOTSTRAPPER
+-----------------------------------------------------------------------------
+This tool will setup a "launcher" host which has all of the infrastructure we
+use to run Consonance.  This launcher host can then launch one or more worker
+VMs to run generic tools and workflows from Dockstore (http://dockstore.org).
 
 This system requires the following:
-* Docker support in your Linux distribution (Ubuntu 14.04 is officially supported by the Consonance Launcher).
-* AWS credentials, if you are using Amazon EC2.
-MSG
+* Docker support in your Linux distribution (Ubuntu 16.04 is officially supported by the Consonance Launcher).
+* Azure credentials, if you are using Microsoft Azure.
+* AWS credentials, if you are using Amazon AWS.
+* OpenStack credentials, if you are using OpenStack.
 
-## Commented text
-#* A GNOS key (or keys) which are used to both download Docker images for our workflows, dependencies, as well as data from from GNOS servers used in the project.
-#  Please ensure that these files are in ~/.gnos
-#* Alternatively (or in addition to) the GNOS keys, a token for downloading workflows, dependencies, as well as donor data files from S3.
+Note: this system currently is configured per cloud, per worker type.  A single
+launcher supporting multiple clouds and multiple worker types is not supported.
+You can, however, run multiple launchers to achieve the dersired result.
+
+Note: by default the ethernet device is assumed to be eth0 and this is used to
+find the IP address of the host. In some instances on AWS the default ethernet
+device is ens3 for example. You can override the eth0 by setting the
+CONSONANCE_ETH_DEV env variable before running this script.
+
+For more information see:
+
+* the main GitHub page: https://github.com/Consonance/consonance
+* the project wiki: https://github.com/Consonance/consonance/wiki
+* the Bootstrapper docs: https://github.com/Consonance/consonance/tree/develop/container-admin
+
+MSG
 
 
 # Ask the user a question and save the answer.
@@ -36,7 +50,7 @@ function ask_question()
 	prev_val=$2
 	val_name=$3
 	answer=''
-	
+
     while [[ -z ${answer// /} ]] ; do
         if [[ -n $prev_val ]] ; then
 			read -ep "${question_str} Previous value: "$'\n' -i "$prev_val" answer
@@ -70,6 +84,18 @@ while [[ "${install_consonance_launcher^^}" != 'Y' &&  "${install_consonance_lau
 				read user_install_docker
 			done
 		fi
+                echo "Installing various apt packages"
+                # need to install regardless
+		set +e
+		sudo apt-get install wget curl ruby-mustache=1.0.2-1 jq git --yes &> install_wget_curl.log
+		install_wget_result=$?
+		set -e
+
+		if [ $install_wget_result -ne  0 ] ; then
+			echo "It looks like there may have been a problem installing or updated wget and curl:"
+			cat install_wget_curl.log
+			exit 1
+		fi
 		if [ "${user_install_docker^^}" = 'Y' ] ; then
 			# Remove eXecute permission from /etc/grub.d/30_os-prober because sometimes the docker installer will hang when this hangs. This has happened in OpenStack
 			# and could happen elsewhere.
@@ -78,25 +104,15 @@ while [[ "${install_consonance_launcher^^}" != 'Y' &&  "${install_consonance_lau
 			fi
 
 			echo "Installing docker..."
-			
-			set +e
-			sudo apt-get install wget curl ruby-mustache=1.0.2-1 jq git --yes &> install_wget_curl.log
-			install_wget_result=$?
-			set -e
-			
-			if [ $install_wget_result -ne  0 ] ; then
-				echo "It looks like there may have been a problem installing or updated wget and curl:" 
-				cat install_wget_curl.log
-				exit 1
-			fi
-			
+
+
 			set +e
 			curl -sSL https://get.docker.com/ | sh &> install_docker.log
 			install_docker_result=$?
 			set -e
-			
+
 			if [ $install_docker_result -ne  0 ] ; then
-				echo "It looks like there may have been a problem installing docker:" 
+				echo "It looks like there may have been a problem installing docker:"
 				cat install_wget_curl.log
 				exit 1
 			fi
@@ -105,21 +121,21 @@ while [[ "${install_consonance_launcher^^}" != 'Y' &&  "${install_consonance_lau
 			sudo wget https://github.com/docker/compose/releases/download/1.8.1/run.sh -O /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose  &> install_compose.log
 			install_compose_result=$?
 			set -e
-			
+
 			if [ $install_compose_result -ne  0 ] ; then
-				echo "It looks like there may have been a problem installing docker compose:" 
+				echo "It looks like there may have been a problem installing docker compose:"
 				cat install_compose.log
 				exit 1
 			fi
 
 
-			
+
 			echo "Done installing docker!"
 			DOCKER_PATH="$(which docker)"
 		else
 			echo "Skipping docker installation..."
 		fi
-		
+
 		if [ -z "$DOCKER_PATH" ] ; then
 			echo "You need to install docker before pulling docker images. Please ensure that docker is properly installed and then re-run this script with the command \"bash install_bootstrap\""
 			exit 1
@@ -139,6 +155,13 @@ while [[ "${run_consonance_launcher^^}" != 'Y' &&  "${run_consonance_launcher^^}
         #Read the config file if it exists and then show previous values...
         if [ -f consonance_launcher_config/compose.config ] ; then
 		source <(jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" consonance_launcher_config/compose.config)
+        fi
+
+        eth_dev=''
+        if [ ! -z $ETH_DEV ] ; then
+                read -ep $'What ethernet device should I pull the IP address from (typically eth0, check with ifconfig). Previous value: \n' -i "$ETH_DEV" eth_dev
+            else
+                read -ep $'What ethernet device should I pull the IP address from (typically eth0, check with ifconfig). \n' eth_dev
         fi
 
         user_cloud_env=''
@@ -178,21 +201,36 @@ while [[ "${run_consonance_launcher^^}" != 'Y' &&  "${run_consonance_launcher^^}
 
 			user_aws_key='user_aws_key'
 			ask_question "What is your AWS Key?" "$AWS_ACCESS_KEY_ID" "AWS Key name" $user_aws_key
-    
+
 			user_aws_secret_key='user_aws_secret_key'
 			ask_question "What is your AWS Secret Key?" "$AWS_SECRET_ACCESS_KEY" "AWS Secret Key name" $user_aws_secret_key
 
 			user_sec_grp='user_sec_grp'
 			ask_question "What is your Security Group?" "$SECURITY_GROUP" "Security Group" $user_sec_grp
 
+			aws_max_spot_price='aws_max_spot_price'
+			ask_question "What is your AWS max spot price?" "$AWS_MAX_SPOT_PRICE" "Max spot price" $aws_max_spot_price
+
+			aws_region='aws_region'
+			ask_question "What is your AWS region (e.g. us-east-1 for Virginia)?" "$AWS_REGION" "AWS region" $aws_region
+
+			aws_zone='aws_zone'
+			ask_question "What is your AWS zone within the selected region (e.g. us-east-1c for the us-east-1 region)?" "$AWS_ZONE" "AWS zone" $aws_zone
+
+			aws_instance_type='aws_instance_type'
+			ask_question "What is your AWS instance type (e.g. c4.2xlarge)?" "$AWS_INSTANCE_TYPE" "AWS instance type" $aws_instance_type
+
+			aws_ami_image='aws_ami_image'
+			ask_question "What is your AWS image (e.g. AMI such as ami-6edd3078 for Ubuntu, we recommend the Ubuntu 16.04 base image that is appropriate for the instance type you just selected)?" "$AWS_AMI_IMAGE" "AWS AMI image" $aws_ami_image
+
 
         elif [ $user_cloud_env == 'Azure' ] ; then
 	        ############################
 	        # AZURE QUESTIONS
-	        ############################        	
+	        ############################
 			user_azure_subscription_id='user_azure_subscription_id'
 			ask_question "What is your Azure subscription?" "$AZURE_SUBSCRIPTION" "Azure subscription" $user_azure_subscription_id
-            
+
 			user_azure_storage_account_name='user_azure_storage_account_name'
 			ask_question "What is your Azure storage account name?" "$AZURE_STORAGE_ACCOUNT" "Azure storage account name" $user_azure_storage_account_name
 
@@ -213,7 +251,7 @@ while [[ "${run_consonance_launcher^^}" != 'Y' &&  "${run_consonance_launcher^^}
 
 			user_azure_virtual_network='user_azure_virtual_network'
 			ask_question "What is the name of the Virtual Network for this fleet?" "$AZURE_VIRTUAL_NETWORK" "Azure Virtual Network Name" $user_azure_virtual_network
-			
+
 			user_azure_location='user_azure_location'
 			ask_question "What Location do you want to use for this fleet?" "$AZURE_LOCATION" "Location" $user_azure_location
 
@@ -248,7 +286,7 @@ while [[ "${run_consonance_launcher^^}" != 'Y' &&  "${run_consonance_launcher^^}
                 read -ep $'What is your OpenStack zone?\n' user_os_zone
             fi
         else
-        	 # Just in case some other value somehow gets in to $user_cloud_env 
+        	 # Just in case some other value somehow gets in to $user_cloud_env
             echo "Unrecognized cloud environment: $user_cloud_env, exiting..."
             exit 1
         fi
@@ -281,8 +319,8 @@ while [[ "${run_consonance_launcher^^}" != 'Y' &&  "${run_consonance_launcher^^}
 	        else
 	            read -ep $'What would you like to name your fleet? If you do not specify a name, a name will be generated randomly for you.\n' user_fleet_name
 	        fi
-       	fi 
-        
+       	fi
+
         # Build a flag for fleet names to get passed to the next script...
         FLEET_NAME_STR=''
         if [ ! -z "$user_fleet_name" ] ; then
@@ -297,9 +335,19 @@ while [[ "${run_consonance_launcher^^}" != 'Y' &&  "${run_consonance_launcher^^}
 		user_fleet_size='user_fleet_size'
 		# Loop until the user gives a valid integer.
 		while [[ -n ${user_fleet_size//[0-9]/} ]] ; do
-		  	user_fleet_size='user_fleet_size'  
+		  	user_fleet_size='user_fleet_size'
 			ask_question "What is the maximum number of worker VMs you want to run in your fleet?" "$FLEET_SIZE" "Maximum fleet size" $user_fleet_size
 			if [[ -n ${user_fleet_size//[0-9]/} ]] ; then
+				echo "Only positive integers are allowed."
+			fi
+		done
+
+		user_fleet_batch_size='user_fleet_batch_size'
+		# Loop until the user gives a valid integer.
+		while [[ -n ${user_fleet_batch_size//[0-9]/} ]] ; do
+		  	user_fleet_batch_size='user_fleet_batch_size'
+			ask_question "What is the maximum number of worker VMs you want to launch at a time?" "$FLEET_BATCH_SIZE" "Maximum fleet batch size" $user_fleet_batch_size
+			if [[ -n ${user_fleet_batch_size//[0-9]/} ]] ; then
 				echo "Only positive integers are allowed."
 			fi
 		done
@@ -317,18 +365,28 @@ while [[ "${run_consonance_launcher^^}" != 'Y' &&  "${run_consonance_launcher^^}
 #            echo "Error is:"
 #            cat ./get_start_launcher_container.err
 #        fi
-				
+
  #       chmod u+x start_launcher_container.sh
  #       CMD_STR="bash start_launcher_container.sh -p $user_pem_path -i $user_consonance_version -e ${user_cloud_env^^} $FLEET_NAME_STR"
 
         # Now write a config for this file.
         [[ -f consonance_launcher_config/compose.config ]] || mkdir -p consonance_launcher_config
-		# Note: You can't have ANY blank lines in .consonance/consonance.config because the python library that will eventually process it does not like blank lines and will fail. 
+		# Note: You can't have ANY blank lines in .consonance/consonance.config because the python library that will eventually process it does not like blank lines and will fail.
+        # we need to override the ethernet device on some systems
+
+                echo "Installing various apt packages"
         cat > consonance_launcher_config/compose.config <<CONFIG
 {
-"LAUNCHER_IP_ADDRESS":"`ifconfig eth0 | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`",
+"ETH_DEV":"${eth_dev}",
+"LAUNCHER_IP_ADDRESS":"`ifconfig ${eth_dev} | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`",
 "AWS_ACCESS_KEY_ID":"${user_aws_key}",
 "AWS_SECRET_ACCESS_KEY":"${user_aws_secret_key}",
+"AWS_MAX_SPOT_PRICE":"${aws_max_spot_price}",
+"FLEET_BATCH_SIZE":"${user_fleet_batch_size}",
+"AWS_REGION":"${aws_region}",
+"AWS_ZONE":"${aws_zone}",
+"AWS_AMI_IMAGE":"${aws_ami_image}",
+"AWS_INSTANCE_TYPE":"${aws_instance_type}",
 "PEM_PATH":"${user_pem_path}",
 "KEY_NAME":"${user_key_name}",
 "FLEET_NAME":"${user_fleet_name}",
@@ -358,12 +416,12 @@ CONFIG
     # template out stuff
     mustache consonance_launcher_config/compose.config aws.config.template > aws.config
     mustache consonance_launcher_config/compose.config bag_params.json.template  > bag_params.json
-    mustache consonance_launcher_config/compose.config config.template  > config 
-    mustache consonance_launcher_config/compose.config youxia_config.template  > youxia_config 
+    mustache consonance_launcher_config/compose.config config.template  > config
+    mustache consonance_launcher_config/compose.config youxia_config.template  > youxia_config
     cat ${user_pem_path} > key.pem
 
-    docker-compose build
-    docker-compose run client
+    sudo docker-compose build
+    sudo docker-compose run client
     elif [ "${run_consonance_launcher^^}" = 'N' ] ; then
         echo "You can run this script at another time to run the consonance launcher"
         exit 0
